apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: litmus-chaos-admin
rules:
- apiGroups: ["core", "apps", "batch", "extensions"]
  resources: ["pods", "deployments", "jobs", "replicasets"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: litmus-chaos-admin-binding
subjects:
- kind: ServiceAccount
  name: litmus-admin
  namespace: litmus
roleRef:
  kind: ClusterRole
  name: litmus-chaos-admin
  apiGroup: rbac.authorization.k8s.io
